[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
    /(
        \.eggs
      | \.git
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | \.vscode
      | _build
      | buck-out
      | build
      | dist
      | venv
      # The following are specific to Black, you probably don't want those.
      | blib2to3
      | tests/data
      | profiling
    )/
'''
